# for GHC-8.0.1
extra-deps:
  - data-stringmap-1.0.1.1
  - json-builder-0.3
  - HaXml-1.24 # only for Windows, comment out for other OSs

resolver: nightly-2016-06-21
# for GHC-7.10.3
# extra-deps:
#   - data-stringmap-1.0.1.1
#   - HaXml-1.24         # only for Windows, comment out for other OSs
# resolver: lts-6.4

packages:
- '../clafer'
- '.'
